### ISSUE TITLE
Create a spinner / working modal when retrieving all deposits

### ISSUE THREAD

**Issue by plinck** [nanderson815/Project3#119]
It takes a couple seconds.   It slowed down more than I hoped when adding jon for first name last name.  We may be able to make that more efficient but also need spinner anyway

**Comment by nanderson815** [comment]
Love this idea -- I think they are fairly easy to implement, will do some research.

**Comment by plinck** [comment]
cool.  I created one in the depostlist component in branch named: bankerDetailUpdates
