### ISSUE TITLE
Reduce credit balance when deposits settle

### ISSUE THREAD

**Issue by nanderson815** [nanderson815/Project3#122]

**Comment by plinck** [comment]
Is this when banker settles transactions?  Shouldn’t balances be:
1.) Credit: cash in safe + cash in archive awaiting settlement - fee
2.) cash in safe : cash in safe (all deposits)
3.) total cash : cash in safe + cash in archive awaiting settlement

**Comment by nanderson815** [comment]
Yes - we need to make sure that the running totals for cash are updated when cash is removed from safe, and credit is reduced when transactions are settled. This relates only to the provisional credit  over time graph- the values everywhere else are calculated based on transaction status.
