### ISSUE TITLE
Get firebase context with Dashboard

### ISSUE THREAD

**Issue by nanderson815** [nanderson815/Project3#26]
need to get access to firebase to be able to read the new "deposits" dataset.

**Comment by plinck** [comment]
Noah - I just created a pull request for my latest.  Its stable and has userRole stuff.  When I saw you issue, I created a starter DepositDB.js file in your dashboard/deposits folder to show you how to grab the context for the Firestore db and do CRUD operations on the deposits collection.  I did a get all and a delete method.  There are class methods so no need to create an object to use.  It basically just a bunch of functions on a class def so you call via `DepositDB.get().then(deposits => {});` etc.  I prefer we encapsulate all our database ops into separate classes like this to keep them out of the REACT components.
