### ISSUE TITLE
Add Signup Page that stores prospect info in MongoDB

### ISSUE THREAD

**Issue by nanderson815** [nanderson815/Project3#37]
this will be used to satisfy the mongo requirement. If a user wants to sign up, we will collect their info and store it in a database. Actual users must be added by us during implementation.

**Comment by plinck** [comment]
Great idea for mongo!

**Comment by nanderson815** [comment]
Sign Up Page complete - Need to create API routes that post to MongoDB

**Comment by nanderson815** [comment]
MongoDB Link Done - need to add from data validation.
