### ISSUE TITLE
Mobile Menu Error : 

### ISSUE THREAD

**Issue by nanderson815** [nanderson815/Project3#43]
Appears to be an issue with Auth for mobile menu

**Comment by plinck** [comment]
Can you give me a tad more detail so I can check this out.  I plan to work on project a couple hours today

**Comment by nanderson815** [comment]
Sure - I am working on it now too while I wait for the locksmith to show up. When clicking the _dashboard_ link on the mobile menu, you are redirected to the landing page, which indicates that the authentication context did not pass correctly. The following error shows up in the console after clicking dashboard: 

index.js:1446 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Home (at AuthUserContext.js:7)
    in Unknown (created by Context.Consumer)

**Comment by plinck** [comment]
OK.  I found those other two things and fixed one, but will look at this

**Comment by plinck** [comment]
Its strange because nav mobile must be getting context since the other authorized links (e.g. admin, account) get properly executed -- just not dashboard.

**Comment by plinck** [comment]
Hang on.  I am fixing things in nav as well.  I have two things to fix.  So, I can put fix in but not sure what you mean be "change the tags in mobile menu to ."

**Comment by plinck** [comment]
OK.  But NavLink does not close mobile menu so I will need to look into that.

**Comment by plinck** [comment]
I found it.  I will update.  I have to call to close for all navlinks and then its all good.  Auth probably had issue with href, since hrefs cause a call all the way back to https server which likely has to refresh context which takes a bit of time for props to propagate

**Comment by plinck** [comment]
OK.  I fixed them all in my current branch - cleanUpRegister process.  I am working on other things in that branch but the fix for this issue in in there
