### ISSUE TITLE
Implement Local Storage at on the Dashboard Component

### ISSUE THREAD

**Issue by nanderson815** [nanderson815/Project3#46]
Currently, the application accesses the firebase every time the component mounts. That means, whenever navigating to and and from the dashboard, the application will make a call to the DB. Store state in local storage to minimize these calls to only once when the applications loads for the first time. This also means an OnSnapshot() listener will need to be added to ensure state, localstorage, and firestore are all in sync.

**Comment by plinck** [comment]
Not sure this is the right approach.  First of all Firebase does a lot of its own caching so even though it is making a call it isn’t necessarily making an expensive dB call.  Also, in the real world this app is multiuser so the only system of record is Firebase so you have to make cAlls To keep things in sync anyway.  I think do think  FB listener should be incorporated but I don’t think you should have to use local storage trying to manually do all the syncing is actually a really big deal in the real world and we need to let Firestore etc handle that heavy lifting.  I haven't thought About it a lot but wanted to make sure you didn’t go too far down that road.  A context may be a better approach anyway.

Frankly, we are getting to the point we here redux May be the true right answer.  But I would say we get all the domain stuff working before we start trying to optimize.   We may end up creating a lot of unnecessary work that we have to redo anyway.

**Comment by nanderson815** [comment]
Thanks for the insight Paul -- this was just me thinking out loud on how to minimize calls.
