### ISSUE TITLE
Make Deposit Item prettier and look like real list with columns etc.

### ISSUE THREAD

**Issue by plinck** [nanderson815/Project3#66]

**Comment by plinck** [comment]
The more details list of deposits is ugly but works.  Also need to add filters / sorters at the top to view by user, or date

**Comment by jjisharry** [comment]
From Team Discussion:

- Deposits should be filterable/sortable by all fields
- Deposits should be flagged as either: "Waiting Settlement","Cleared","Current".
- Export to CSV should be based on filters.
