### ISSUE TITLE
Consider changer 'user' field on deposits to email

### ISSUE THREAD

**Issue by plinck** [nanderson815/Project3#68]
It actually is the users email but it is named user.  I had a big issue this morning because user is also the name of the context prop for authenticated user info.  When getting our of props it didn't know which one to get since it was passed as props from deposits and from context.

Also, it is the user's email so it would be more clear

But several code blocks would need to change in DepositDB AND OTHER REACT COMPONENBTS

**Comment by nanderson815** [comment]
working on this now.
