### ISSUE TITLE
Handle the pending and clearing process - Add "Clear" Button to Banker 

### ISSUE THREAD

**Issue by nanderson815** [nanderson815/Project3#71]

**Comment by nanderson815** [comment]
Will remove all transaction data for testing/demo purposed.

**Comment by plinck** [comment]
Need to make sure we consider what we do with deposits etc to make sure we can still have history for graphs etc.  Do we mark deposits as active or closed etc or do we archive into archived/closed collections

**Comment by plinck** [comment]
IS this what it should do:
Step 1 - SEND CASH/Empty Safe
- Mark all *current* deposit transactions as *cash sent to bank*
- Have another total somewhere for *cash in transit, waiting settlement*
Step 2 - CLEAR/Settlement - This is when deposit hits bank account
- Mark all *cash sent to bank/awaiting settlement* deposits as cleared
- Change the total credit and total deposits to match *current* deposits

We need to make a choice of whether we have a flag or enum on all deposits that tells whether deposit is cleared, awaiting settlement, or current. We need to keep the deposit history, but we need to make sure they are setup so they go to the appropriate total.

**Comment by plinck** [comment]
All done except I still need to do the CLEAR process that clears them all deposits are settled.
